Add unit test dashboard circle progress bar
DTS-STN/sc-digital-centre pull request #194
Opened 2022-02-10 15:48 UTC by nabil386

## [DCWC-XXX](https://jira-dev.bdm-dev.dts-stn.com/browse/DCWC-XXX) (Jira Issue)

### Description

List of proposed changes:

-Add unit test for dashboard 
-Add unit test for circle progress bar

### What to test for/How to test

### Additional Notes

2022-02-10 19:26 UTC, nabil386 commented on components/atoms/CircleProgressBar.test.js
> +jest.mock('next/router', () => ({
got cleaned up

2022-02-14 15:12 UTC, arsanig requested changes
Files should be under `__tests__/`

2022-02-14 16:47 UTC, nabil386 commented
tests have been moved to __tests__

2022-02-14 19:38 UTC, arsanig approved these changes

2022-02-14 19:38 UTC, merged