extracted btn-primary, added btn styles from design lib
DTS-STN/sc-digital-centre pull request #20
Opened 2021-09-23 20:34 UTC by TishamIslam

## [DC-XXX](https://jira-dev.bdm-dev.dts-stn.com/browse/DC-XXX) (No Jira Issue)

### Description
Just made stuff more readable and made it so that it'd reflect the [canada.ca design](https://www.canada.ca/home.html) better 

List of proposed changes:
- [Design library button styles](https://www.figma.com/file/TodbPq5LF1G6l1E3Kx2qPP/GC-Design-Library?node-id=19%3A0) added into the project
- Extracted btn-primary component, can add the other btns as needed

### Addtional Notes
Please take a look at the extracted component and point out anything that should be removed.

2021-09-24 13:44 UTC, MarcoGoC commented
I suggest using ActionButton as per alpha

2021-09-24 13:54 UTC, shewood requested changes
Maybe hold off on the role based colours until we can discuss with the designers as there are several duplicate colours in the list and it will get confusing later on.

2021-09-27 13:44 UTC, DaceyTom2 requested changes

2021-09-27 13:44 UTC, DaceyTom2 commented on pages/index.js
>                  id="french-button"
The buttons padding got a bit wonky
![image](https://user-images.githubusercontent.com/69208837/134920464-d445982b-aed5-4d91-8715-6c9ae15599bb.png)

2021-10-01 14:29 UTC, closed without merging