Creating a Middleware
DTS-STN/sc-digital-centre pull request #324
Opened 2022-05-06 16:05 UTC by s-laugh

## [DCWC-1692](https://jira-dev.bdm-dev.dts-stn.com/browse/DCWC-1692) (Jira Issue)

This should only be moving code, not changing it.

Removing the UniversalBenefit.js and putting the chunks of code in better places.

2022-05-09 12:14 UTC, DaceyTom2 requested changes

2022-05-09 13:24 UTC, s-laugh commented on pages/api/programData/_middleware.js
> +export function CreateGenericBenefitObj(
move to lib - will re-add _middleware.js when auth is merged

2022-05-09 13:24 UTC, s-laugh commented on pages/api/programData/ei.js
> +]
Move to it's own consts file.

2022-05-09 13:29 UTC, s-laugh commented on pages/api/programData/ei.js
> +    return null
Not sure about that... This isn't actually used as an API call as it's called from 'GetServerSideProps' which is on the same server; doesn't make sense for it to call itself; instead this current implementation is just a function reference.

2022-05-09 15:31 UTC, s-laugh commented on pages/dashboard.js
> +  if (eiData) usersBenefts.push(eiData)
Yes.... yes it should. Would it be alright to manage that in another PR?

2022-05-10 18:12 UTC, DaceyTom2 commented on pages/dashboard.js
> +  if (eiData) usersBenefts.push(eiData)
Sure thing

2022-05-10 18:26 UTC, s-laugh commented on pages/api/programData/cpp.js
> +export default async function GetCPPProgramData() {
solving when moved to proper API in another PR

2022-05-10 18:26 UTC, s-laugh commented on pages/api/programData/ei.js
> +    return null
Yup, will do in another PR

2022-05-11 13:33 UTC, DaceyTom2 approved these changes
Looks good!

2022-05-11 13:34 UTC, merged