Expand/Collapse Card Interaction
DTS-STN/sc-digital-centre pull request #500
Opened 2022-07-27 16:31 UTC by CurtisUnderwood

## Description of Changes

### [ADO Work Item XXX](https://dev.azure.com/VP-BD/DECD/_workitems/edit/XXX)

### What to test for/How to test

### Additional Notes
- Added transition for expansion/collapse of universal benefit card
-
## Checklist

- [ ] Tests added for key features and bugs
- [ ] Deployment working

2022-07-28 13:46 UTC, TishamIslam commented
Not sure what happened, but I think it's having a weird interaction with the EI card since it has two sections of tasks.
![image](https://user-images.githubusercontent.com/45071113/181520615-ac39b144-6862-4c4f-b35b-d784fe38e591.png)

After expansion it behaves normally.

2022-07-29 15:00 UTC, shewood requested changes
I see the same issue as Tisham but only on Firefox and only for that card.

2022-07-29 16:12 UTC, shewood commented
I think the only change you need to make on the previous version is this to get it to do what we want.  
Change 
 block: 'start',
to
 block: 'nearest',

2022-08-03 14:38 UTC, CurtisUnderwood commented
> I see the same issue as Tisham but only on Firefox and only for that card.

Good catch, seemed to be an issue only on Firefox can you confirm it's resolved?

> I think the only change you need to make on the previous version is this to get it to do what we want.

I think this may be a question for the PO, the card expansion ticket asks for a transition animation on the card dropdown which required a bit of a re-organization. Block 'nearest' would just remove the scroll, both are viable just depends if we want the animation.

2022-08-04 12:20 UTC, shewood commented on components/molecules/UniversalBenefitCard.js
> +          <div className="  ">
Looks good.
Any reason for not keeping the id on the tasklist?

2022-08-08 12:48 UTC, merged